# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimulationState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("engine_enabled", models.BooleanField(default=False)),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_stopped_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("generation", models.PositiveIntegerField(default=0)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={"verbose_name": "simulation state"},
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_id", models.CharField(db_index=True, max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("hostname", models.CharField(max_length=128)),
                ("ip_address", models.GenericIPAddressField(protocol="IPv4", unique=True)),
                ("snmp_port", models.PositiveIntegerField(default=161)),
                ("snmp_version", models.CharField(default="2c", max_length=8)),
                ("community", models.CharField(default="public", max_length=64)),
                (
                    "community_alias",
                    models.CharField(
                        help_text="Alternate community equal to the device id for host-port access.",
                        max_length=64,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("router", "Router"),
                            ("switch", "Switch"),
                            ("firewall", "Firewall"),
                            ("generic", "Generic SNMP device"),
                        ],
                        max_length=32,
                    ),
                ),
                ("vendor", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=64)),
                ("sys_object_id", models.CharField(max_length=128)),
                ("sys_descr", models.TextField()),
                ("location", models.CharField(default="Datacenter Lab / Rack A", max_length=128)),
                ("contact", models.CharField(default="netops@lab.local", max_length=128)),
                ("serial_number", models.CharField(blank=True, default="", max_length=64)),
                (
                    "traffic_profile",
                    models.CharField(
                        choices=[("high", "HIGH"), ("medium", "MEDIUM"), ("low", "LOW")],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "reachability",
                    models.CharField(
                        choices=[("up", "UP / REACHABLE"), ("down", "DOWN / UNREACHABLE")],
                        default="up",
                        max_length=8,
                    ),
                ),
                ("interface_count", models.PositiveIntegerField(default=4)),
                ("interfaces", models.JSONField(blank=True, default=list)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["device_id"]},
        ),
    ]
