"""Export Datadog Agent SNMP configuration from the current lab inventory."""

from __future__ import annotations

from pathlib import Path

from django.conf import settings

from simulator.engine.config import load_simulator_config
from simulator.models import Device


def device_tags(device: Device) -> list[str]:
    return [
        f"device_id:{device.device_id}",
        f"device_type:{device.device_type}",
        f"traffic_profile:{device.traffic_profile}",
        f"vendor:{device.vendor.lower()}",
        f"model:{device.model}",
        f"lab_status:{'reachable' if device.is_reachable else 'unreachable'}",
        "env:snmp-lab",
    ]


def render_snmp_conf(devices: list[Device] | None = None) -> str:
    devices = list(devices if devices is not None else Device.objects.all())
    cfg = load_simulator_config()
    lines = [
        "# Generated by the SNMP Network Device Simulator.",
        "# Copy to /etc/datadog-agent/conf.d/snmp.d/conf.yaml and restart the Agent.",
        "#",
        "# Unreachable devices are included on purpose so Datadog can raise",
        "# snmp.can_check / NDM reachability alerts.",
        "",
        "init_config:",
        "  loader: core",
        "  use_device_id_as_hostname: true",
        "",
        "instances:",
    ]
    if not devices:
        lines.append("  # No simulated devices yet. Run: python manage.py simulator start")
        return "\n".join(lines) + "\n"

    for device in devices:
        lines.append(f"  - ip_address: '{device.ip_address}'")
        lines.append(f"    port: {device.snmp_port}")
        lines.append("    snmp_version: 2")
        lines.append(f"    community_string: '{device.community}'")
        lines.append(f"    timeout: 3")
        lines.append(f"    retries: 2")
        lines.append("    tags:")
        for tag in device_tags(device):
            lines.append(f"      - '{tag}'")
        lines.append("")
    return "\n".join(lines)


def render_autodiscovery_snippet() -> str:
    cfg = load_simulator_config()
    cidr = cfg["network"]["device_cidr"]
    community = cfg["snmp"]["community"]
    port = cfg["snmp"]["port"]
    return f"""# Add this block to /etc/datadog-agent/datadog.yaml
# Autodiscovery scans the simulator subnet. Unreachable devices will fail
# SNMP checks and appear down in Network Device Monitoring.

network_devices:
  autodiscovery:
    workers: 50
    discovery_interval: 3600
    loader: core
    use_device_id_as_hostname: true
    configs:
      - network_address: {cidr}
        loader: core
        snmp_version: 2
        port: {port}
        community_string: '{community}'
        tags:
          - 'env:snmp-lab'
          - 'source:snmp-simulator'
"""


def render_host_port_conf(host: str = "127.0.0.1") -> str:
    """Community-based access via the published host UDP port (works on Docker Desktop)."""
    cfg = load_simulator_config()
    host_port = cfg["snmp"]["host_port"]
    devices = list(Device.objects.all())
    lines = [
        "# Alternative Datadog config using the host-mapped UDP port.",
        f"# Each device is selected by community string (device-id) on {host}:{host_port}.",
        "# Use this when the Datadog Agent cannot route to 10.200.1.0/24.",
        "",
        "init_config:",
        "  loader: core",
        "  use_device_id_as_hostname: true",
        "",
        "instances:",
    ]
    for device in devices:
        lines.append(f"  - ip_address: '{host}'")
        lines.append(f"    port: {host_port}")
        lines.append("    snmp_version: 2")
        lines.append(f"    community_string: '{device.community_alias}'")
        lines.append("    tags:")
        for tag in device_tags(device):
            lines.append(f"      - '{tag}'")
        lines.append("")
    return "\n".join(lines) + "\n"


def write_datadog_exports() -> dict[str, Path]:
    out = Path(settings.SIMULATOR_DATADOG_DIR)
    out.mkdir(parents=True, exist_ok=True)
    files = {
        "conf.yaml": render_snmp_conf(),
        "datadog.yaml.snippet": render_autodiscovery_snippet(),
        "conf.hostport.yaml": render_host_port_conf(),
    }
    paths = {}
    for name, content in files.items():
        path = out / name
        path.write_text(content, encoding="utf-8")
        paths[name] = path
    return paths
